trigger: none
pr: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: swellaby-private-extension-validation.shellcheck-private.install-shellcheck.install-shellcheck@0
  displayName: 'Install ShellCheck'
  inputs:
    version: stable

- task: swellaby-private-extension-validation.shellcheck-private.shellcheck.shellcheck@0
  displayName: 'Run ShellCheck analysis'
  inputs:
    targetFiles: 'passing/**/*.sh'
