pool:
  name: Hosted macOS
steps:
- task: install-shellcheck@0
  displayName: 'Install ShellCheck'
  inputs:
    version: stable

- task: shellcheck@0
  displayName: 'Run ShellCheck analysis'
  inputs:
    targetFiles: 'failing/**/*.sh'
