pool:
  vmImage: vs2017-win2016

steps:
- task: install-shellcheck@0
  displayName: 'Install ShellCheck'
  inputs:
    version: stable

- task: shellcheck@0
  displayName: 'Run ShellCheck analysis'
  inputs:
    targetFiles: 'passing/**/*.sh'
